---
title: "UKHSAdashR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{UKHSAdashR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(UKHSAdashR)
```

## Example

To obtain the daily reported cases of COVID-19, use the following:

``` r
get_data(
  theme = "infectious_disease",
  sub_theme = "respiratory",
  topic = "COVID-19",
  geography_type = "Nation",
  geography = "England",
  metric = "COVID-19_cases_casesByDay"
) |> 
head()
```

```
               theme   sub_theme    topic geography_type geography geography_code                    metric metric_group stratum sex age year month epiweek       date metric_value in_reporting_delay_period
1 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     1       5 2020-01-30            1                     FALSE
2 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     1       5 2020-01-31            0                     FALSE
3 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     2       5 2020-02-01            0                     FALSE
4 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     2       5 2020-02-02            1                     FALSE
5 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     2       6 2020-02-03           18                     FALSE
6 infectious_disease respiratory COVID-19         Nation   England      E92000001 COVID-19_cases_casesByDay        cases default all all 2020     2       6 2020-02-04            0                     FALSE
```

If an argument is not supplied within `get_data()`, then a list of possible arguments will be returned:

``` r
get_data(
  theme = "infectious_disease",
  sub_theme = "respiratory",
  topic = "",
  geography_type = "Nation",
  geography = "England",
  metric = "COVID-19_cases_casesByDay"
)
```

```
Topic:

[1] "Adenovirus"    "COVID-19"      "hMPV"          "Influenza"    
[5] "Parainfluenza" "Rhinovirus"

```



